alpha_fixed_emb: 0.95
asso_func: iou
aw_off: false
aw_param: 0.5
cmc_off: false
delta_t: 3
det_thresh: 0.5
embedding_off: false
inertia: 0.2
iou_thresh: 0.3
max_age: 30
min_hits: 3
w_association_emb: 0.75
Q_xy_scaling: 0.01
Q_s_scaling: 0.0001
